Eval:
  Exclude:
    - "Rakefile"

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 30

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - "bin/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Naming/FileName:
  Exclude:
    - "bin/*"

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/CaseEquality:
  Enabled: false
