version: "2"

services:
  dev:
    image: ruby:2.6@sha256:f38fce2b70ba23e90d6397995bea8419b86dd3f20b73846681adb52c63c0b002
    volumes:
      - .:/work
      - ruby2.6-bundle-cache:/usr/local/bundle
    environment:
      BUNDLE_GEMFILE: /work/Gemfile
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_REGION: ap-southeast-2
    working_dir: /work
    command: ["bash"]

volumes:
  ruby2.6-bundle-cache:
    external: true
